recipes-sota/aktualizr/aktualizr_git.bb

The previously specified version no longer exists.

Bump garage-sign to 0.7.4-2.

---

conf/distro/sota.conf.inc
conf/layer.conf

Fixes https://github.com/advancedtelematic/meta-updater/issues/825.
FYI @shr-project I'm not really supporting the old advancedtelematic repos anymore; this is the central repo now.
We have separate gatesgarth and hardknott repos here, although they are identical to the current master. Do we need a separate honister branch now as well, or is that still compatible with the changes here? I don't have a great way to test master these days, so I'm somewhat reliant on you or others to confirm if this is working.

Fix/ats 825/kirkstone

---

recipes-sota/aktualizr/aktualizr_git.bb

* github decided that nobody should use git://
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
and starting today all the builds were failing to fetch the metadata
layers from github like:
2021-11-01T18:53:26 INFO _main_ Updating [meta-ros]
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
this was just a "test" as they said:
"November 2, 2021: We'll also run several short brownouts on this date."
and it will be completely disabled on January 11 2022.
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

aktualizr: use https protocol to fetch it

---

classes/sota.bbclass

* it's not clear why sota replaces gnutls with openssl support for curl
and it should be rather DISTRO policy doing this (openssl is enabled
by default and if some DISTRO chooses gnutls for whatever reason,
enabling sota probably shouldn't just overrule that decision,
especially as the remove operator from
PACKAGECONFIG:remove:pn-curl
is impossible to undo)
* add intermediate variables to make it possible to "undo" this by
setting both to empty in your distro config and replace 'ssl' with
'openssl'
* it was introduced in:
https://github.com/uptane/meta-updater/commit/9d9b6a8eb297e7e90a680730bfc5068deb19a138
* 'ssl' PACKAGECONFIG was removed in:
https://github.com/openembedded/openembedded-core/commit/eef6c45fc6ec0a496791123e8ba2f400a5d9d468
Signed-off-by: Martin Jansa …

[kirkstone] sota.bbclass: update for renamed ssl PACKAGECONFIG in curl recipe

---

classes/sota.bbclass

* it's not clear why sota replaces gnutls with openssl support for curl
and it should be rather DISTRO policy doing this (openssl is enabled
by default and if some DISTRO chooses gnutls for whatever reason,
enabling sota probably shouldn't just overrule that decision,
especially as the remove operator from
PACKAGECONFIG:remove:pn-curl
is impossible to undo)
* add intermediate variables to make it possible to "undo" this by
setting both to empty in your distro config
* it was introduced in:
https://github.com/uptane/meta-updater/commit/9d9b6a8eb297e7e90a680730bfc5068deb19a138
Modified from the original master commit since ssl has only been renamed
to openssl in master; see
https://github.com/openembedded/openembedded-core/commit/eef6c45fc6ec0a496791123e8ba2f400a5d9d468
Cherry-picked and …

sota.bbclass: add variables to override ssl support for curl

---

recipes-extended/ostree/ostree/0001-ostree-pull-set-request-timeout.patch
recipes-extended/ostree/ostree_%.bbappend

Set a timeout for an overall request processing in order to avoid an
ostree pull/fetch API call or CLI command hang.  The timeout value can
be specified via an env variable OSTREE_CURL_TIMEOUT, if not defined, or
equal 0 or it cannot be converted to a long type then the default value
is set.
Based on 2b742b96341a245b2a1c66bb93a837345e533c63 in meta-lmp; see
https://github.com/foundriesio/meta-lmp/pull/382 and
https://github.com/foundriesio/meta-lmp/pull/391.
See also https://github.com/ostreedev/ostree/issues/2383.

ostree: patch to setup a curl request timeout

---

classes/sota.bbclass

Since OE-Core c39452bf6 the default crypto is already openssl, so no
need for the custom remove/append logic to remove gnutls anymore.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

sota: drop curl packageconfig settings for openssl

---

classes/sota.bbclass
classes/sota_m3ulcb.bbclass
classes/sota_porter.bbclass
classes/sota_qemux86-64.bbclass

While most boards will indeed use wic format for images, it is not
something that is strictly required when using sota, as we do have
some BSPs that require only the ext4 image instead (e.g. tegra).
Wic should be included, when needed, at the machine config instead (or
via sota_<machine>.bbclass).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

classes/sota: no need to add wic when sota is enabled

---

recipes-extended/ostree/ostree/0001-ostree-pull-set-request-timeout.patch

* adjust for 2020.7 version used in gatesgarth
hardknott is using 2021.1, honister 2021.3

ostree: adjust 0001-ostree-pull-set-request-timeout.patch

---

recipes-sota/aktualizr/aktualizr_git.bb

Backport https://github.com/uptane/meta-updater/pull/38 and https://github.com/uptane/meta-updater/pull/39 from master branch to fix aktualizr-native build with newer host distributions.

aktualizr: bump SRCREVs

---

recipes-sota/asn1c/asn1c.bb

* fixes:
ERROR: asn1c-native-0.9.28-r0 do_populate_lic: QA Issue: asn1c-native: No generic license file exists for: BSD in any provider [license-exists]
after ambiguous BSD license text was removed in:
https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=14d4c007c49652d836d325a12bdbcd3bfa42e6d5
Signed-off-by: Martin Jansa <martin2.jansa@lgepartner.com>

asn1c: use BSD-2-Clause instead of ambiguous BSD

---

recipes-sota/aktualizr/aktualizr_git.bb

Due switch to OpenSSL 3 (>= kirkstone), the pkcs11 engine path needs
to be changed to follow the correct version id.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

aktualizr: use updated pkcs11 engines path for openssl 3

---

classes/image_types_ota.bbclass

This allows external layers to include additional task dependencies for
additional customizations done via IMAGE_CMD:ota-ext4:append.
No functional changes, default dependency list stays the same.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

image_types_ota: use += when setting task depends for image_ota_ext4

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/aktualizr-tmpfiles.conf

By default, /tmp gets cleaned every 10 days, which causes libaktualizr to lose its temporary files that it relies on for openssl certificates. This results in curl error 58. Restarting the service/library resolves the problem, but even better is to prevent the files from being cleaned up.
Inspired by https://github.com/foundriesio/meta-lmp/pull/330, but closer to the source.
Same as https://github.com/uptane/meta-updater/pull/46 but for master.

aktualizr: Exclude tmpfiles used for certs from systemd cleanup.

---

classes/image_types_ostree.bbclass

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
(cherry picked from commit 286d4ea374ee2c60d1576fada8bbe100a6566a4d)
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

image_types_ostree: show the errorcode on the push failed warning

---

classes/image_types_ostree.bbclass

The bbfatal_log is like bbfatal, except prevents the suppression of the error log by bitbake's UI.
When 'garage-sign targets push' fails all attempts is better to show their sterr+stdout logs.
This will change the error log from this:
```
ERROR: lmp-base-console-image-1.0-r0 do_image_garagesign: garage-sign fatal error with code 1
ERROR: lmp-base-console-image-1.0-r0 do_image_garagesign: ExecutionError('/oe/build/tmp/work/intel_corei7_64-lmp-linux/lmp-base-console-image/1.0-r0/temp/run.do_image_garagesign.1590854', 1, None, None)
ERROR: Logfile of failure stored in: /oe/build/tmp/work/intel_corei7_64-lmp-linux/lmp-base-console-image/1.0-r0/temp/log.do_image_garagesign.1590854
ERROR: Task (/oe/layers/meta-lmp/meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb:do_image_garagesign …
```

image_types_ostree: use bbfatal_log when do_image_garagesign fails

---

classes/image_types_ostree.bbclass

- image_types_ostree: introduce GARAGE_PUSH_RETRIES
This add the possibility to change the number of retries
of the "garage-sign targets push"
- image_types_ostree: introduce GARAGE_PUSH_RETRIES_SLEEP
This add the possibility to sleep a maximum defined random
time after "garage-sign targets push" fails

Improve the garage-sign targets push resilience

---

classes/sota_sanity.bbclass

The oe-core change got backported today to langdale and kirkstone:
https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=06e088ef6e961f05ca600612adcc71bff91f09be
so we need the changes from https://github.com/uptane/meta-updater/pull/61 to be applied there as well.

sota_sanity.bbclass: don't use copy_data()

---

recipes-extended/ostree/ostree/0001-ostree-fetcher-curl-set-a-timeout-for-an-overall-req.patch
recipes-extended/ostree/ostree_%.bbappend

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

ostree: refresh patches for v2022.7

---

classes/image_types_ostree.bbclass

Before the introduction of the ostree_rmdir_helper the '/var' content is removed uncondictional
but new they are removed if they are directories and not symbolic link.
To make it consistent we will remove everything in '/var' with the exception of 'var/local'.
This will also warn about all content deleted from '/var' that has been silent until now
so running bitbake in verbose mode will produce:
```
WARNING: lmp-base-console-image-1.0-r0 do_image_ostree: Data in 'var' directory is not preserved by OSTree. Consider moving it under '/usr'
var/volatile
var/lib
var/log
var/tmp
var/cache
+ rm -vrf var
removed directory 'var/volatile'
removed directory 'var/lib'
removed 'var/log'
removed 'var/tmp'
removed directory 'var/cache'
removed directory 'var'
+ mkdir var
```

image_types_ostree: ostree_rmdir_helper: fix regression in removing /var symbolic links

---

classes/image_types_ostree.bbclass

Backport https://github.com/uptane/meta-updater/pull/69

Backport [kirkstone]: image_types_ostree: ostree_rmdir_helper: fix regression in removing /var symbolic links

---

classes/image_types_ostree.bbclass

Both requires special handling as these directories are required by the do_rootfs task (used while bootstrapping the image via packages), and can't be removed via recipes.
This fixes the var/lib and var/cache warnings when removing var.

image_types_ostree: remove var/lib and var/cache before var

---

classes/image_types_ostree.bbclass

Backport https://github.com/uptane/meta-updater/pull/71

Backport [kirkstone]: image_types_ostree: remove var/lib and var/cache before var

---

recipes-connectivity/nfs-utils/nfs-utils/tmpfiles.conf
recipes-connectivity/nfs-utils/nfs-utils_%.bbappend

```
WARNING: lmp-base-console-image-1.0-r0 do_image_ostree: Data in 'var/lib' directory is not preserved by OSTree. Consider moving it under '/usr' | var/lib/nfs
var/lib/nfs/etab
var/lib/nfs/statd
var/lib/nfs/statd/sm
var/lib/nfs/statd/state
var/lib/nfs/statd/sm.bak
var/lib/nfs/rmtab
var/lib/nfs/v4recovery
```

nfs-utils: update the systemd tmpfiles and fix the warning

---

recipes-connectivity/nfs-utils/nfs-utils/tmpfiles.conf
recipes-connectivity/nfs-utils/nfs-utils_%.bbappend

```
WARNING: lmp-base-console-image-1.0-r0 do_image_ostree: Data in 'var/lib' directory is not preserved by OSTree. Consider moving it under '/usr' | var/lib/nfs
var/lib/nfs/etab
var/lib/nfs/statd
var/lib/nfs/statd/sm
var/lib/nfs/statd/state
var/lib/nfs/statd/sm.bak
var/lib/nfs/rmtab
var/lib/nfs/v4recovery
```
(cherry picked from commit 012e7eda5423595c77277ff70fdfdecb846c27a5)

Backport [kirkstone]: nfs-utils: update the systemd tmpfiles and fix the warning

---

recipes-sota/fit-conf/fit-conf.bb

On board using a fitImage, poky's upstream change from the following commit:
https://git.yoctoproject.org/poky/commit/?id=ab6b5e97cebe19938baa403da6307ca320294b3a
inserted a regression of the fit-conf.bb recipe.
Causing a U-boot boot fault displaying this type of message:
```
Could not find configuration node
ERROR: can't get kernel image!
Unknown command '!' - try 'help'
resetting ...
```
fitImage configuration labels are now prefixed with conf- instead of conf@.
This commit incorporates this modification for the fit-conf.bb recipe.
fix #75

fit-conf: fix u-boot boot fail

---

classes/image_types_ostree.bbclass
recipes-core/images/initramfs-ostree-image.bb

- image_types_ostree: IMAGE_NAME_SUFFIX is now directly included
_The IMAGE_NAME_SUFFIX is now directly included in both IMAGE_NAME and IMAGE_LINK_NAME._
- initramfs-ostree-image: IMAGE_NAME_SUFFIX should by emptry for initramfs
_INITRAMFS_IMAGE_NAME stay as before but it assumes that all
images used as initramfs will set IMAGE_NAME_SUFFIX to empty._
https://git.yoctoproject.org/poky/commit/?id=6f6c79029bc2020907295858449c725952d560a1

IMAGE_NAME_SUFFIX changed upstream in oe-core

---

classes/image_types_ostree.bbclass

Disable sending the manifest, because the torizon backend doesn't support the format, and add explicit 'uses network' annotations.

fix garage-push

---

classes/image_types_ostree.bbclass

https://github.com/uptane/meta-updater/pull/67 is first merged in kirkstone but it is also needed on master.

[Forward-port] Fix garage push

---

recipes-sota/aktualizr/aktualizr_git.bb

Update the SRCREV to fix a build failure ('uint8_t' does not name a type) when using poky master branch.
c90723717 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #105 from uptane/merge-upstream-docs 7dff8e1c2 Fixed coverage and static checks jobs (#1837) d35e774c0 Fixed libOstree links (#1833)
efd939295 Merge pull request #101 from uptane/fix-shellcheck-complaint b2ee72ebf Merge pull request #102 from DengkeDu/fix-build-error-v2 05b1af5e0 aktualizr: fix build error 'uint8_t' does not name a type 317f2ee65 (origin/fix-shellcheck-complaint) Remove leftover cruft from load tests. 69dfff995 Fix shellcheck complaint that somehow didn't show up until now. 60e2ffbff Merge pull request #96 from cajun-rat/multibyte-part1 b32833489 Fix test flake by picking a random port
28ed95cd9 …

aktualizr: bump SRCREV

---

conf/include/bblayers/sota.inc

Fix ERROR: Layer 'filesystems-layer' depends on layer 'networking-layer', but this layer is not enabled in your configuration

sota.inc: add meta-networking to the layers

---

classes/sota.bbclass
recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb

The recipe ostree-kernel-initramfs currently  triggers a kernel rebuild because the module-base.bbclass explicitly requires it and the `noexec` used on the recipe still uses what is in the task `depends` flag
```
$ grep depends meta/classes-recipe/module-base.bbclass
do_configure[depends] += "make-mod-scripts:do_compile"
```

ostree-kernel-initramfs: fix kernel rebuild 

---

classes/image_types_ota.bbclass

EXTRA_IMAGECMD is using hardcoded values like "-i 4096". Use a soft assignment to make it easier to override.
Currently, we can still override but we need to use more statements (:append / :remove). Hence it's less convenient.

image_types_ota: use a soft assignment for EXTRA_IMAGECMD:ota-ext4

---

classes/image_types_ota.bbclass

Using FSTYPES to add the do_image_wic dependency instead of sota DISTRO_FEATURES. It allows to easily extend do_image_ota to other file systems. For instance, I successfully extended the class to use btrfs.
e.g. extending to btrfs will look like
inherit image_types_ota
[...]
do_image_wic[depends] += "${@bb.utils.contains('IMAGE_FSTYPES', 'ota-btrfs', '%s:do_image_ota_btrfs' % d.getVar('PN'), '', d)}"

image_types_ota: rely on FSTYPES to add do_image_wic dependency

---

classes/image_types_ostree.bbclass

Commit 60c3f7267ff51caeaf6d74a5f445ee4bcf2f0ae8 added logic to specifically maintain the contents of /var/local into the generated image but a minor error in a condition prevented that from happening; here we fix that condition to meet the original goal.
See https://github.com/uptane/meta-updater/pull/69#discussion_r1523604247

image_types_ostree: fix logic to maintain /var/local contents

---

classes/image_types_ostree.bbclass

Commit 60c3f7267ff51caeaf6d74a5f445ee4bcf2f0ae8 added logic to specifically maintain the contents of /var/local into the generated image but a minor error in a condition prevented that from happening; here we fix that condition to meet the original goal.
See https://github.com/uptane/meta-updater/pull/69#discussion_r1523604247

image_types_ostree: fix logic to maintain /var/local contents (cherry pick from master branch)

---

conf/layer.conf

The master branch is not more compatible with the kirkstone, at least [1] breaks invalidates compatibility.
Also remove the other intermediate releases as the master branch is mostly tested with the oe-core master.
[1] https://github.com/uptane/meta-updater/pull/78

layer.conf: add scarthgap compatibility and drop some old releases

---

conf/layer.conf
recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb
recipes-connectivity/nfs-utils/nfs-utils_%.bbappend
recipes-sota/aktualizr/aktualizr-collectd.bb
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/config/aktualizr-auto-reboot.bb
recipes-sota/config/aktualizr-binary-pacman.bb
recipes-sota/config/aktualizr-disable-send-ip.bb
recipes-sota/config/aktualizr-log-debug.bb
recipes-sota/config/aktualizr-polling-interval.bb
recipes-sota/config/aktualizr-virtualsec.bb
recipes-sota/ostree-initrd/ostree-initrd.bb
recipes-sota/ostree/ostree-booted_1.0.bb
recipes-support/slcand-start/slcand-start.bb
recipes-support/softhsm-testtoken/softhsm-testtoken.bb
recipes-support/systemd-journald-persistent/systemd-journald-persistent.bb
recipes-test/demo-config/primary-config.bb
recipes-test/demo-config/secondary-config.bb
recipes-test/demo-network-config/network-config.inc
recipes-test/demo-network-config/primary-network-config.bb
recipes-test/demo-network-config/secondary-network-config.bb

On Yocto master (5.1 onwards)  it is no longer supported to use S = "${WORKDIR}". [1]
Following the 5.1 release notes [2], S should now be "${WORKDIR}/sources", and references for ${WORKDIR} in recipe tasks should either be ${UNPACKDIR} or ${S}.
[1] https://git.openembedded.org/openembedded-core/commit/?h=master&id=32cba1cc916ad530c5e6630a927e74ca6f06289b
[2] https://docs.yoctoproject.org/next/qmigration-guides/migration-5.1.html#s-workdir-no-longer-supported

recipes: fix S = "${WORKDIR}" no longer supported on master

---

classes/image_types_ostree.bbclass
classes/sota.bbclass

To enable usage of the Uptane's 'ota-tuf' repository for uptane-sign, we need to change this task. Since in more recent releases there, the tool name has changed from 'garage-sign' to 'uptane-sign'.
This way, we set the name of the tool used in a customizable variable, defaulting to 'garage-sign', and if anyone wants to use the latest version of this tool (given Aktualizr was also refactored), they just need to set this new variable with the tool name.

image_types_ostree: refactor garagesign task

---

classes/image_types_ostree.bbclass
classes/sota.bbclass
recipes-sota/aktualizr/aktualizr_git.bb

Cherry-picking to Scarthgap the commits made to master on 2 different PR:
https://github.com/uptane/meta-updater/pull/104
https://github.com/uptane/meta-updater/pull/105

Refactor garagesign task and fetch its binary from a new location

---

recipes-extended/ostree/ostree_%.bbappend

I am working to enable ostree in my yocto build using meta-updater. 
I see a build issue related to ostree-ptest when ptest is enabled as part of the distro features. It seems like ostree-ptest has a dependency on ostree-trivial-httpd and it breaks on removing soup from PACKAGECONFIG. 
This change is to remove soup only if ptest is not enabled.
Build, boot up and ota update are successful with this change.

Remove soup from PACKAGECONFIG only if ptest is not enabled

---

recipes-extended/ostree/ostree_%.bbappend

ostree-ptest has a dependency on ostree-trivial-httpd which gets compiled only if soup is enabled.
Signed-off-by: Roshan Sivakumar <quic_roshs@quicinc.com>
(cherry picked from commit 68865c1738badf86c6aaad87f22661e96ee5c4ac)

[kirkstone] ostree: Remove soup from PACKAGECONFIG only if ptest is not enabled

---

recipes-extended/ostree/ostree_%.bbappend

ostree-ptest has a dependency on ostree-trivial-httpd which gets compiled only if soup is enabled.
Signed-off-by: Roshan Sivakumar <quic_roshs@quicinc.com>
(cherry picked from commit 68865c1738badf86c6aaad87f22661e96ee5c4ac)

[scarthgap] ostree: Remove soup from PACKAGECONFIG only if ptest is not enabled

---

classes/image_types_ostree.bbclass

Added selinux as arg to tar utility which will preserve the selinux labels if they are present else it will NOP.
Signed-off-by: Ravi Kumar Siddojigari <quic_rsiddoji@quicinc.com>

image_types_ostree: add selinux support when packing rootfs image

---

classes/image_types_ostree.bbclass

instead of directly calling tar utility using IMAGE_CMD_TAR
Signed-off-by: Ravi Kumar Siddojigari <quic_rsiddoji@quicinc.com>
(cherry picked from commit 624672dea3edf8febbe3059df24b4908647c905d)

image_types_ostree: correct calling of tar utility with IMAGE_CMD_TAR (cherry pick from master branch)

---

classes/image_types_ostree.bbclass

This commit (https://github.com/uptane/meta-updater/commit/925dcfca94f0d5c2057eafc584d8f0838ac8faa9) started using IMAGE_CMD_TAR instead of hardcoding the tar command inside of IMG_CMD:ostree task. But the second instance of this variable is missing the '$' to reference it causing this build error:
```
10-29:22:18:15  | /workdir/oe/tmp/work/colibri_imx6-tdx-linux-gnueabi/torizon-core-docker/1.0-r0/temp/run.do_image_ostree.361095: 156: {IMAGE_CMD_TAR}: not found
10-29:22:18:15  | WARNING: exit code 127 from a shell command.
10-29:22:18:15  NOTE: recipe torizon-core-docker-1.0-r0: task do_image_ostree: Failed
10-29:22:18:15  ERROR: Task (/workdir/oe/build/conf/../../layers/meta-toradex-torizon/recipes-images/images/torizon-core-docker.bb:do_image_ostree) failed with exit code '1'
```

[master] image_type_ostree: fix reference of IMAGE_CMD_TAR variable

---

classes/image_types_ostree.bbclass

Cherry-picked from https://github.com/uptane/meta-updater/pull/117.

[kirkstone] image_type_ostree: fix reference of IMAGE_CMD_TAR variable

---

classes/image_types_ota.bbclass

Enhance the handling of special characters in the cmdline such as semicolons, which bash cannot handle correctly during build time.

image_types_ota.bbclass: Improve cmdline handling

---

recipes-sota/aktualizr/files/aktualizr-tmpfiles.conf

"X" only excludes the directory from being cleaned-up. The contents of the directory can still be cleaned-up, resulting in curl error 58.
Change to "x" which recursively protects the directory and files.

aktualizr: adjust tmpfile config

---

recipes-extended/ostree/ostree/0001-ostree-fetcher-curl-set-a-timeout-for-an-overall-req.patch
recipes-sota/asn1c/files/skeletons_dir_fix.patch

Since now it is required for patches to have 'Upstream-Status', I've added 'Upstream-Status: Inappropriate [embedded specific]' to those patches, since they've been created for a long time and doesn't seem to have been upstreamed.

patches: add the required Upstream-Status to this layer patches

---

recipes-devtools/valgrind/files/bug344802-unhandled-0xec510f1e.patch

(cherry picked from commit a6263085c28e3efc3848880494f85ead5471630e)

[scarthgap:backport] valgrind: add missing patch-status

---

recipes-sota/aktualizr/aktualizr_git.bb

(cherry picked from commit 3947a64f3d0d46f915868cfbc464684a35cae08c)

aktualizr: fix pre dunfell syntax override

---

recipes-sota/ostree-initrd/files/init.sh

This change relocates the /run mount point from initramfs (/run) to the real root filesystem (sysroot/run). This ensures that systemd does not remount it during switchroot if it detects an existing mount point. Consequently, all contents of /run will be transferred to the real root filesystem.
This adjustment resolves the issue of mounting sysroot as  read-only. During the execution of ostree-remount.service, the system checks /run/ostree-booted to determine if sysroot should be mounted as read-only.

ostree-initrd: move /run mount point to sysroot/run

---

recipes-extended/ostree/ostree_%.bbappend

Hi,
Since ostree v2023.5 and specifically commit
https://github.com/ostreedev/ostree/commit/d6799ecc243befcf714bcf54dbbd41da13a6e290
Building with static linking forces the usage of
ostree-prepare-root-static which is checking that it is executed as PID1.
This is incompatible with the usage of an initramfs.
----
I changed and tested this on scarthgap branch.
Unlike in https://github.com/uptane/meta-updater/pull/106, I did not need to bring the whole ostree to make it work, but as said, I only tested it on scarthgap.

ostree: Fix usage of ostree-prepare-root for initramfs

---

recipes-extended/ostree/ostree_%.bbappend

Since ostree v2023.5 and specifically commit
https://github.com/ostreedev/ostree/commit/d6799ecc243befcf714bcf54dbbd41da13a6e290
Building with static linking forces the usage of
ostree-prepare-root-static which is checking that it is executed as PID1.
This is incompatible with the usage of an initramfs.
(cherry picked from commit abd60ecf39c30b9e9ebb47565234e34f1eb6e5ef)

[scarthgap] ostree: Fix usage of ostree-prepare-root for initramfs

---

recipes-sota/ostree-initrd/files/init.sh

This PR cherry-picks two commits from master to scarthgap that both address
the relocation of the /run mount point from initramfs (/run) to the real root
filesystem (sysroot/run).

ostree-initrd: Move /run Mount Point to sysroot/run (Cherry-pick: 7ac47ea, 3de3b4f)
